version: '3.8'
services:
  app:
    container_name: app
    build:
      context: ./app
      target: debug
    ports:
      - "8080:8080"
    env_file:
      - ./app/.env
    volumes:
      - ./app:/usr/src/app
    environment:
      - TZ=Europe/London
      - GF_INSTALL_PLUGINS=redis-datasource
    depends_on:
      - redis
    networks:
      - sce-net-cloud
  redis:
    container_name: redis-cloud
    image: redis/redis-stack-server:latest
    ports:
      - "6380:6379"
    volumes:
      - redis-data-cloud:/var/lib/redis-stack
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      # - /var/lib/redis-stack
    environment:
      - TZ=Europe/London
    networks:
      - sce-net-cloud
    command: redis-stack-server /usr/local/etc/redis/redis.conf
    
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - TZ=Europe/London
      - GF_INSTALL_PLUGINS=redis-app
    depends_on:
      - redis
    networks:
      - sce-net-cloud
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards


      
networks:
  sce-net-cloud:
    driver: bridge

volumes:
  redis-data-cloud:
  grafana-data:
