version: '3.8'
services:
  app:
    container_name: app
    build:
      context: .
      target: debug
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    environment:
      - TZ=Europe/London
    depends_on:
      - redis
    networks:
      - sce-net-cloud
  redis:
    container_name: redis-cloud
    image: redis/redis-stack:latest
    ports:
      - "6380:6379"
    volumes:
      - redis-data-cloud:/data
    environment:
      - TZ=Europe/London
      - REDIS_SAVE=900 1 150 10 60 10000
      - REDIS_APPENDONLY=yes
    networks:
      - sce-net-cloud

networks:
  sce-net-cloud:
    driver: bridge

volumes:
  redis-data-cloud:
