version: '3.8'
services:
  app:
    container_name: app
    build:
      context: .
      target: debug
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    environment:
      - TZ=Europe/London
    depends_on:
      - redis
    networks:
      - sce-net-cloud
  redis:
    container_name: redis-cloud
    image: redis/redis-stack-server:latest
    ports:
      - "6380:6379"
    volumes:
      - redis-data-cloud:/var/lib/redis-stack
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      # - /var/lib/redis-stack
    environment:
      - TZ=Europe/London
    networks:
      - sce-net-cloud
    command: redis-stack-server /usr/local/etc/redis/redis.conf
    

networks:
  sce-net-cloud:
    driver: bridge

volumes:
  redis-data-cloud:
