version: '3.7'
services:
  nodered:
    # build: .
    # image: kuzurik/node-red-sce
    image: nodered/node-red
    ports:
      - "1880:1880"
    environment:
      - TZ=Europe/London
    volumes:
      - ./nodered/data:/data
    networks:
      - sce-net
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
    environment:
      - TZ=Europe/London
    networks:
      - sce-net
    volumes:
      - edge-redis-data:/data

networks:
  sce-net:
    driver: bridge

volumes:
  edge-redis-data:
