# version: '3.7'
services:
  nodered:
    container_name: nodered
    image: nodered/node-red
    ports:
      - "1880:1880"
    environment:
      - TZ=Europe/London
    volumes:
      - ./nodered/data:/data
    networks:
      - sce-net-edge
    depends_on:
      - redis
  mosquitto: # Topics (`node/${global.nodeId}/data/`, payload) and (`node/${circuit.nodeId}/${circuit.circuitId}/relay`, 1)
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - sce-net-edge
    environment:
      - TZ=Europe/London
    # restart: unless-stopped
  edge-server:
    container_name: server
    build:
      context: ./server
      target: debug
    ports:
      - "8081:8081"
    environment:
      - TZ=Europe/London
    networks:
      - sce-net-edge
    env_file:
      - ./server/.env
    volumes:
      - ./server:/usr/src/app
      - ./nodered/data/certificates:/usr/src/app/certificates
    depends_on:
      - nodered
      - redis
      - mosquitto
  redis:
    container_name: redis
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
    environment:
      - TZ=Europe/London
      - REDIS_SAVE=30 1
      - REDIS_APPENDONLY=yes
    networks:
      - sce-net-edge
    volumes:
      - redis-data:/data
      # - /data
      

networks:
  sce-net-edge:
    driver: bridge

volumes:
  redis-data:
