version: '3.7'
services:
  nodered:
    container_name: nodered
    image: nodered/node-red
    ports:
      - "1880:1880"
    environment:
      - TZ=Europe/London
    volumes:
      - ./nodered/data:/data
    networks:
      - sce-net-edge
    depends_on:
      - redis
  edge-server:
    container_name: edge-server
    build:
      context: ./server
      target: debug
    ports:
      - "8081:8080"
    environment:
      - TZ=Europe/London
    networks:
      - sce-net-edge
    env_file:
      - ./server/.env
    depends_on:
      - nodered
      - redis
  redis:
    container_name: redis-edge
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
    environment:
      - TZ=Europe/London
    networks:
      - sce-net-edge
    volumes:
      - edge-redis-data:/data

networks:
  sce-net-edge:
    driver: bridge

volumes:
  edge-redis-data:
