# version: '3.7'
services:
  nodered:
    container_name: nodered
    image: nodered/node-red
    ports:
      - "1880:1880"
    environment:
      - TZ=Europe/London
    volumes:
      - ./nodered/data:/data
    networks:
      - sce-net-edge
    depends_on:
      - mosquitto

  mosquitto: # Topics (`node/${global.nodeId}/data/`, payload) and (`node/${circuit.nodeId}/${circuit.circuitId}/relay`, 1)
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - sce-net-edge
    environment:
      - TZ=Europe/London
    # restart: unless-stopped

  edge-server:
    container_name: server
    build:
      context: ./server
      target: debug
    ports:
      - "8081:8081"
    environment:
      - TZ=Europe/London
    networks:
      - sce-net-edge
    env_file:
      - ./server/.env
    volumes:
      - ./server:/usr/src/app
      - ./nodered/data/certificates:/usr/src/app/certificates
    depends_on:
      - redis
      - mosquitto

  redis:
    container_name: redis
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    environment:
      - TZ=Europe/London
    networks:
      - sce-net-edge
    volumes:
      - redis-data:/var/lib/redis-stack
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      # - /var/lib/redis-stack
    command: redis-stack-server /usr/local/etc/redis/redis.conf

  grafana:
    # image: grafana/grafana:latest
    image: grafana/grafana-dev:12.4.0-21003774845-ubuntu
    container_name: grafana-edge
    ports:
      - "3002:3000"
    env_file:
      - ./server/.env
    environment:
      - TZ=Europe/London
      - GF_INSTALL_PLUGINS=redis-app
    depends_on:
      - redis
    networks:
      - sce-net-edge
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      # - ./grafana/provisioning/alerting:/etc/grafana/provisioning/alerting
      

networks:
  sce-net-edge:
    driver: bridge

volumes:
  redis-data:
  grafana-data:
