apiVersion: 1

datasources:
  - name: Redis-Cloud
    type: redis-datasource
    access: proxy
    url: redis://192.168.0.41:6380
    jsonData:
      client: standalone
      poolSize: 5
      timeout: 10
    editable: true